/**
 * Renders documents from data/documents.json into the #documents container.
 *
 * The JSON is generated by scripts/sync-drive.mjs (run via GitHub Action),
 * which lists files from Bara Fibers Google Drive-mappar och grupperar
 * dem per kategori och år.
 */

(async function () {
  const container = document.getElementById('documents');
  if (!container) return;

  const CATEGORIES = [
    { key: 'styrelsemoten', label: 'Styrelseprotokoll', icon: '🗒️' },
    { key: 'arsmoten', label: 'Årsstämmor', icon: '📋' },
    { key: 'stadgar', label: 'Stadgar & övriga dokument', icon: '📜' },
  ];

  const MIME_ICON = {
    'application/pdf': '📄',
    'application/vnd.google-apps.document': '📝',
    'application/vnd.google-apps.spreadsheet': '📊',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '📊',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': '📝',
    'application/vnd.google-apps.folder': '📁',
    'image/png': '🖼️',
    'image/jpeg': '🖼️',
  };

  const iconFor = (mime) => MIME_ICON[mime] || '📎';

  const formatDate = (iso) => {
    if (!iso) return '';
    try {
      return new Date(iso).toLocaleDateString('sv-SE', {
        year: 'numeric', month: 'short', day: 'numeric',
      });
    } catch {
      return '';
    }
  };

  let data;
  try {
    const res = await fetch('data/documents.json', { cache: 'no-cache' });
    if (!res.ok) throw new Error('HTTP ' + res.status);
    data = await res.json();
  } catch (err) {
    container.innerHTML = `
      <div class="doc-error">
        <strong>Kunde inte ladda dokumentlistan.</strong><br>
        <span class="text-muted">Försök igen senare eller besök föreningens Google Drive direkt.</span>
      </div>`;
    console.error('Failed to load documents.json:', err);
    return;
  }

  container.innerHTML = '';

  if (data.lastUpdated) {
    const info = document.createElement('p');
    info.className = 'text-muted';
    info.style.fontSize = '0.875rem';
    info.style.marginBottom = '1.5rem';
    info.innerHTML = `Senast uppdaterad från Google Drive: <strong>${formatDate(data.lastUpdated)}</strong>`;
    container.appendChild(info);
  }

  let totalFiles = 0;

  CATEGORIES.forEach((cat) => {
    const catData = data[cat.key];
    if (!catData) return;

    const section = document.createElement('div');
    section.className = 'doc-category';

    const heading = document.createElement('h3');
    heading.innerHTML = `<span>${cat.icon}</span> ${cat.label}`;
    section.appendChild(heading);

    // Two shapes: array of files (flat) OR object keyed by year
    if (Array.isArray(catData)) {
      if (catData.length === 0) {
        section.appendChild(emptyNote());
      } else {
        section.appendChild(renderList(catData));
        totalFiles += catData.length;
      }
    } else {
      const years = Object.keys(catData).sort((a, b) => b.localeCompare(a));
      if (years.length === 0) {
        section.appendChild(emptyNote());
      } else {
        years.forEach((year) => {
          const files = catData[year];
          if (!files || files.length === 0) return;
          const yearWrap = document.createElement('div');
          yearWrap.className = 'doc-year';
          const yearLabel = document.createElement('div');
          yearLabel.className = 'doc-year-label';
          yearLabel.textContent = year;
          yearWrap.appendChild(yearLabel);
          yearWrap.appendChild(renderList(files));
          section.appendChild(yearWrap);
          totalFiles += files.length;
        });
      }
    }

    container.appendChild(section);
  });

  if (totalFiles === 0) {
    container.innerHTML = `
      <div class="doc-empty">
        <strong>Inga dokument hittades.</strong><br>
        <span class="text-muted">Dokumentlistan synkas dagligen från föreningens Google Drive.</span>
      </div>`;
  }

  function emptyNote() {
    const p = document.createElement('div');
    p.className = 'doc-empty';
    p.textContent = 'Inga dokument tillgängliga ännu.';
    return p;
  }

  function renderList(files) {
    const ul = document.createElement('ul');
    ul.className = 'doc-list';
    files
      .slice()
      .sort((a, b) => (b.modifiedTime || '').localeCompare(a.modifiedTime || ''))
      .forEach((f) => {
        const li = document.createElement('li');
        const a = document.createElement('a');
        a.className = 'doc-item';
        a.href = f.webViewLink || f.url || '#';
        a.target = '_blank';
        a.rel = 'noopener';

        const icon = document.createElement('span');
        icon.className = 'doc-icon';
        icon.textContent = iconFor(f.mimeType);

        const info = document.createElement('span');
        info.className = 'doc-info';
        const name = document.createElement('span');
        name.className = 'doc-name';
        name.textContent = f.name;
        info.appendChild(name);

        if (f.modifiedTime) {
          const meta = document.createElement('span');
          meta.className = 'doc-meta';
          meta.textContent = formatDate(f.modifiedTime);
          info.appendChild(meta);
        }

        const arrow = document.createElement('span');
        arrow.className = 'doc-arrow';
        arrow.textContent = '↗';

        a.appendChild(icon);
        a.appendChild(info);
        a.appendChild(arrow);
        li.appendChild(a);
        ul.appendChild(li);
      });
    return ul;
  }
})();
